#!/sbin/busybox sh

if [ "a$2" != "a" ];then
  scaling_min_freq_charging=$2
fi

sed -i 's/scaling_min_freq_charging=.*/scaling_min_freq_charging=$2/g' /data/.agat/default.profile

echo $scaling_min_freq_charging
